parameters:
  hubdrop.class:  HubDrop\Bundle\Service\HubDrop

  hubdrop.github_username: "%hubdrop.github_username%"
  hubdrop.github_organization: "%hubdrop.github_organization%"
  hubdrop.github_authorization_key: "%hubdrop.github_authorization_key%"
  hubdrop.drupal_username: "%hubdrop.drupal_username%"
  hubdrop.url: "%hubdrop.url%"

services:
  hubdrop:
    class:        "%hubdrop.class%"
    arguments: ["%hubdrop.github_username%", "%hubdrop.github_organization%", "%hubdrop.github_authorization_key%", "%hubdrop.drupal_username%", "%hubdrop.url%", @router, @session]
